extends: airbnb-base
rules:
  no-console: 1
  no-unused-vars: 1
  no-undef: 1
  prefer-const: 1
  no-use-before-define: 1
  no-extra-semi: 1
  default-case: 1
  no-var: 1
  semi: 1
  comma-dangle: 1
  no-restricted-syntax: 1
  no-prototype-builtins: 1
  prefer-destructuring: 1
